### ISSUE TITLE
Order of properties in the decoded_resource

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CredentialRegistry#214]
@rsaksida @science 
Per Stuart Sutton, the @context property should be the first property in a registry document, typically followed by @id, and then @graph. 
We publish documents in the latter order, but in the decoded_resource property, the order is changed to @id, @graph, and then @context.
example on staging server:
https://staging.credentialengineregistry.org/ce-registry/envelopes/0fb9235d-3673-4fda-9f66-8a53efdc2be0
Payload send to registry before being encoded in an envelope:
![image](https://user-images.githubusercontent.com/26332112/46889251-a78f4c00-ce28-11e8-99de-38fe6e708642.png)

contents in decoded_resource:
![image](https://user-images.githubusercontent.com/26332112/46889313-dc030800-ce28-11e8-90f1-7d8295819591.png)

Is this a result how a registry process does deserialization to the decoded_resource?
Can this process be changed to retain the original order with the @context first?

We would like to resolve this before republishing all of the production documents.

**Comment by stuartasutton** [comment]
@cwd-mparsons, the exact order of `@id` and `@context` outside the `@graph` doesn't matter so long as they precede the  `@graph` (i.e., are outside). 

The `@context` in the decoded_source needs to be corrected. `@context` inside the `@graph` applies ONLY to the resource in which it is embedded. It would not apply to any other resources (like bNodes) inside that `@graph` unless declared in each resource!

**Comment by rsaksida** [comment]
To clarify, this is only about the _order_, right?

It should be:

```
@id:,
@context:,
@graph:
```

I'm asking because @stuartasutton's mentioned elements being inside/outside the graph so I'm unsure whether this is structural or about order only.

Technically the JSON spec [doesn't guarantee order](https://www.json.org/):

> An object is an **unordered** set of name/value pairs.

We're not doing anything special encoding/decoding the payload, but the JSON parser's output is unpredictable as the spec defines objects as unordered sets.

**Comment by rsaksida** [comment]
I can, of course, preserve order in a particular way with some manual intervention. I'll work on that.

**Comment by rsaksida** [comment]
I've pushed a fix for the orders issue to sandbox and staging - can you check if it looks okay and if anything else needs to be changed? Let me know if I can deploy to production. Thanks.

**Comment by cwd-mparsons** [comment]
@rsaksida The order is now proper in the decoded_resource - thanks.

However, I see that the order when accessed via the /graph/ url, is still incorrect. I republished the following today to verify:
https://staging.credentialengineregistry.org/graph/ce-8e7a46af-9fd7-4547-8778-46fc182e9518

So apparently this process is different from that used to decode a resource. 
This order will need to also be changed so that the order is @context, @id, and @graph. 
Is this a change that can be implemented today?
If not, is it related to how data is published? That is can I proceed with the bulk republish tonight?

**Comment by rsaksida** [comment]
I've just implemented a fix for that - it's live on staging. It's not necessary to republish.

**Comment by cwd-mparsons** [comment]
Thank you very much. Now as no good deed goes unpunished, we have another request. 
The @context properly appears first for a /graph/ URL.
The main resource under an @graph object, can also be accessed directly using the /resource/---CTID---
https://staging.credentialengineregistry.org/resources/ce-8e7a46af-9fd7-4547-8778-46fc182e9518

The latter has the @context property inserted at the end of the document. As the latter is not part of the original document, there must be some code the appends the property when retrieved via /resource/.

We need this to be inserted as the first property, before @id.
![image](https://user-images.githubusercontent.com/26332112/47039562-d7e92a00-d149-11e8-8894-a4d21c26ca83.png)

**Comment by siuc-nate** [comment]
Note that the above _only_ applies when the resource is accessed via the /resources/ endpoint.  The current /graph/ implementation that exclusively has the context at the top of the graph is correct.

**Comment by rsaksida** [comment]
Nice catch. I've updated the `/resources` endpoint as well and deployed it to production.
