### ISSUE TITLE
Errors encountered during publishing refer to ctdl:PropertyName, rather than ceterms:PropertyName

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CredentialRegistry#26]
@andersoncardoso 
While attempting to publish a test credential, I receive the following error:

> Resource JSON Schema validation errors: ["ctdl:url : is required", "ctdl:name : is required", "ctdl:ctid : is required", "@type : did not match one of the following values: ctdl:Credential, ctdl:Badge, ctdl:DigitalBadge, ctdl:OpenBadge, ctdl:Certificate, ctdl:ApprenticeshipCertificate, ctdl:JourneymanCertificate, ctdl:MasterCertificate, ctdl:Certification, ctdl:Degree, ctdl:AssociateDegree, ctdl:BachelorDegree, ctdl:DoctoralDegree, ctdl:ProfessionalDoctorate, ctdl:ResearchDoctorate, ctdl:MasterDegree, ctdl:Diploma, ctdl:GeneralEducationDevelopment, ctdl:SecondarySchoolDiploma, ctdl:License, ctdl:MicroCredential, ctdl:QualityAssuranceCredential"]

Notes:

- "is required" errors refer to, for example, ctdl:url, and not ceterms:Url (which is now SubjectWebpage)
- The actual credential type (see attached) is ceterms:MasterDegree, yet the validation is referring to types prefixed with ctdl

[2017-03-20_credential_1209_payload.txt](https://github.com/CredentialEngine/CredentialRegistry/files/856231/2017-03-20_credential_1209_payload.txt)

**Comment by leolara** [comment]
@coffeejunk should look into this as well

**Comment by leolara** [comment]
@cwd-mparsons @siuc-nate 

A bit off topic, I think https://gist.github.com is a good tool top post here payloads, examples, snipets, etc

**Comment by andersoncardoso** [comment]
Hi @cwd-mparsons ,

So the schema (on the old repo at least, which is the one the staging server is pointing to) it's the old one, with `ctdl` and all. 
The change I made on the `config.json` it's only related to designating a schema for the payload, not related at all with the schema itself. 
So unless you pass the `skip_validation=true` to save the resources, the system will provide errors according to the schema it has. 

Have you updated the schema somehow? (either via code, or via api)

PS: to give  an overall view: 
```
request  --1-->  [unwrap envelope, check JWT etc] --2--> [check "@type" on 'config.json' to find the schema]  --3--> [validate using the corresponding json-schema] --4-->[save OR return errors]
```
before we were getting errors from (2), i.e: checking the config for an available schema.
now we are on (3), i.e: errors from the schema itself.

**Comment by cwd-mparsons** [comment]
@andersoncardoso 
I have not made any changes to the registry schema. 
I am not sure what the next steps are. Based on your example above of the 4 steps, is the issue that the actual **validation schema used by the registry** has not been changed to use the new, ceterms based, schema?

**Comment by leolara** [comment]
@cwd-mparsons there is an API to change the schema, but I think it is more convenient for you if we update the schame, the thing is are you using the staging deployment? In that case we can update the schema, but if you are running your own deployment you will have to do it yourself.

@andersoncardoso @coffeejunk can you update the schema in the staging deployment? The correct ones are:

http://credreg.net/ctdl/schema/validation/Credential/json?asGroup=true
http://credreg.net/ctdl/schema/validation/Agent/json?asGroup=true
http://credreg.net/ctdl/schema/validation/AssessmentProfile/json?asGroup=true
http://credreg.net/ctdl/schema/validation/LearningOpportunityProfile/json?asGroup=true

**Comment by leolara** [comment]
@andersoncardoso also from your mention please change the staging server to track this repositiory

https://github.com/CredentialEngine/CredentialRegistry/issues/30

Parsons and Nate, need to test these schemas:

http://credreg.net/ctdl/schema/validation/Credential/json?asGroup=true
http://credreg.net/ctdl/schema/validation/Agent/json?asGroup=true
http://credreg.net/ctdl/schema/validation/AssessmentProfile/json?asGroup=true
http://credreg.net/ctdl/schema/validation/LearningOpportunityProfile/json?asGroup=true

with our current code

**Comment by cwd-mparsons** [comment]
@leolara 
Yes, we are using the staging deployment, not a local deployment.

**Comment by leolara** [comment]
@cwd-mparsons we are working to make the staging deployment use this code and also have your Schema. Unfortunately, it is not so yet.

I will let you know as soon as it is.

cc/ @andersoncardoso @coffeejunk

**Comment by andersoncardoso** [comment]
Hi, 
I wasn't able to open a PR with the new json-schemas version yet, because the schemas seem to be broken 
(for pushing a PR our tests has to pass, and currently 55 tests are failing with them). 
I tried to load each schema on this validator http://www.jsonschemavalidator.net/ and it indicates several errors, so this might be a good tool to iterate until you refine a version we can test. 
(For example:  all of them shown at least one undefined property with the prefix `schema:`, e.g: `schema:Email`, among others)

The current branch for this is here: https://github.com/CredentialEngine/CredentialRegistry/compare/ceterms-schemas?expand=1

**Comment by leolara** [comment]
@andersoncardoso ok, @coffeejunk will try to do this.

And **I** will work on the validation problems with  @cwd-mparsons @siuc-nate

**Comment by leolara** [comment]
@andersoncardoso I created this: https://github.com/CredentialEngine/CredentialRegistry/issues/40 for the errors you found

**Comment by leolara** [comment]
@coffeejunk the JSON schemas seem ok now

**Comment by cwd-mparsons** [comment]
@coffeejunk @leolara 
Does this mean the json validation schema is ready to be tested, ie for us to do 'test' publishing?
I believe that sometime last week, a goal of Tuesday (Mar 28, 2017) was suggested for a completion date.

**Comment by leolara** [comment]
@cwd-mparsons I think we are almost there. Isn't it, @coffeejunk ?

The JSON schema problems were fixed the last time I tried, and @coffeejunk added them as fixtures, but we are still understanding how this is all tied together

**Comment by leolara** [comment]
@cwd-mparsons I thought it was easier, I said Tuesday but it seems it is taking more time.

**Comment by cwd-mparsons** [comment]
@leolara 
Not a problem, I was still getting errors while testing, and didn't want to report errors if there had not been any code updates.

**Comment by coffeejunk** [comment]
The json schemas have been updated: http://lr-staging.learningtapestry.com/api/schemas/info

**Comment by leolara** [comment]
@coffeejunk awesome!!

cc/ @cwd-mparsons @siuc-nate

**Comment by cwd-mparsons** [comment]
@leolara @coffeejunk 
I have been able to do simple publishing of each of credential, organization, assessment and learning opportunity. 
Any publishing related issues will be documented with a new issue, so I am closing this issue.
