### ISSUE TITLE
Promote an updated JSON schema

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/CredentialRegistry#268]
I corrected a misspelling of OccupationalTask.
Please promote the following to the sandboax and staging servers:
https://github.com/CredentialEngine/CTDL_Json_Validation_Schema/blob/master/NavySchema-2019-09-17/navyOccupationalTask.json

**Comment by cwd-mparsons** [comment]
@rsaksida Romulo, would you be able to do this request Alex is probably sleeping by now.

**Comment by excelsior** [comment]
The schema was fixed yesterday, the envelopes were reindexed.

**Comment by cwd-mparsons** [comment]
Alex
Thanks. I see the new schema is updated:
https://staging.credentialengineregistry.org/schemas/navy/occupational_task

I noticed the old schema file still exists, even though it is not listed on the schema page:
https://staging.credentialengineregistry.org/schemas/navy/occupation_task

**Comment by excelsior** [comment]
I've deleted the wrong schema. It shouldn't have affected anything anyway.

**Comment by cwd-mparsons** [comment]
Thanks. I under stood there was no issue, just checking
