### ISSUE TITLE
Query timing out

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/CredentialRegistry#670]
The following query runs for a very long time, and eventually times out:
```
{
	"ceterms:instructionalProgramType": "search:anyValue",
	"ceterms:ownedBy": "search:anyValue",
	"ceterms:offeredBy": "search:anyValue"
}
```

![image](https://github.com/CredentialEngine/CredentialRegistry/assets/21346519/f841c330-91f8-49b9-956c-c3ef72f246af)

This was discovered while communicating with a partner. That partner isn't using the search API directly, but I need this kind of query to work in order to answer some questions that partner has.

Also, the error returned is an HTML error (maybe generated at a different layer of server processing?) instead of a JSON error, which would further complicate error handling downstream.

**Comment by siuc-nate** [comment]
Two more that are timing out:
```
{
	"@type": "ceasn:Competency",
	"^ceterms:targetNode":	{
		"^ceterms:targetCompetency": {
			"^ceterms:requires": "search:anyValue"
		}
	}
}
```

```
{
	"@type": "ceasn:Competency",
	"^ceterms:targetNode": {
		"^ceterms:teaches": {
			"^ceterms:targetLearningOpportunity": {
				"^ceterms:requires": "search:anyValue"
			}
		}
	}
}
```

The second one works (though it does take a very long time, over a minute and a half) if I specify a resource rather than using `search:anyValue`, so the problem appears to be related to that rather than to the reverse property lookups:
```
{
	"@type": "ceasn:Competency",
	"^ceterms:targetNode": {
		"^ceterms:teaches": {
			"^ceterms:targetLearningOpportunity": {
				"^ceterms:requires": {
					"ceterms:ctid": "ce-98d29a1e-58ea-49cd-9308-49a1863a9362"
				}
			}
		}
	}
}
```

**Comment by jeannekitchens** [comment]
@edgarf @excelsior the above competency queries are too slow.  We're working with a customer and this is an issue getting in the way.

**Comment by jeannekitchens** [comment]
@edgarf @excelsior @science from a customer, just now...."We’re making great progress retrieving your data, but I have to say the retrieval time is on the extraordinary side, and not in a good way."

The slowness of the above referenced queriesis a major blocker.

**Comment by edgarf** [comment]
This task is now having full attention from Alex

**Comment by jeannekitchens** [comment]
@excelsior @edgarf @science please provide us an update today.  Typically software companies partnering with Credential Engine have a short sprint window of opportunity.  When a team allocates time dedicated to building out Credential Registry integration we need to be sure they're not running into barriers.  As a reminder, customers and wen test queries here https://credreg.net/quickstart/queryhelper.  This morning, I'm getting no results for all four of the above competency queries. I'm getting this error, "Error parsing results: One or more errors occurred.; A task was canceled."

The Credential Finder's competency search also does a direct Registry search.  The Competency Framework search is way too slow this morning. This impacts our team and other users.  Very often, we have meetings, demos, etc.. and use the Finder. The competency framework search is expetionally slow today and doesn't look to be bringing back all of the frameworks.  https://credentialfinder.org/search?searchType=competencyframework

**Comment by excelsior** [comment]
@siuc-nate I deployed the search engine optimizations. I haven't found any regressions, let me know if you notice any discrepancies in the results.

**Comment by siuc-nate** [comment]
Thanks. Some quick tests show there is still a lot of variation. Any idea what's causing it?:

The original query from the first post took between 10 and 27 seconds across 3 runs:
```
{
	"ceterms:instructionalProgramType": "search:anyValue",
	"ceterms:ownedBy": "search:anyValue",
	"ceterms:offeredBy": "search:anyValue"
}
```
![image](https://github.com/CredentialEngine/CredentialRegistry/assets/21346519/6f264448-215b-4dcb-b368-b3a98eb86c8f)

This query takes about 2 seconds each on 3 runs, which should be okay I think:
```
{
	"@type": "ceasn:Competency",
	"^ceterms:targetNode":	{
		"^ceterms:targetCompetency": {
			"^ceterms:requires": "search:anyValue"
		}
	}
}
```

This one takes just over six seconds across 3 runs, which is a little slow: 
```
{
	"@type": "ceasn:Competency",
	"^ceterms:targetNode": {
		"^ceterms:teaches": {
			"^ceterms:targetLearningOpportunity": {
				"^ceterms:requires": "search:anyValue"
			}
		}
	}
}
```

This one takes less than two seconds, which is pretty good:
```
{
	"@type": "ceasn:Competency",
	"^ceterms:targetNode": {
		"^ceterms:teaches": {
			"^ceterms:targetLearningOpportunity": {
				"^ceterms:requires": {
					"ceterms:ctid": "ce-98d29a1e-58ea-49cd-9308-49a1863a9362"
				}
			}
		}
	}
}
```

This query (from Jeanne's post) took between 29 and 37 seconds across 3 runs:
```
{
	"@type": "ceasn:Competency",
	"^ceasn:skillEmbodied": {
	"^ceterms:targetNode": {
	 		"^ceterms:teaches": {
				"^ceterms:targetLearningOpportunity": {
					"^ceterms:requires": {
						"ceterms:ctid": "ce-98d29a1e-58ea-49cd-9308-49a1863a9362"
					}
				}
			}
		}
	}
}
```
![image](https://github.com/CredentialEngine/CredentialRegistry/assets/21346519/7cfac92b-989b-4a66-81b4-427f9cf9e296)

**Comment by jeannekitchens** [comment]
@excelsior @edgarf @siuc-nate 

**This query is still not usable.  It results in an error, "Error parsing results: One or more errors occurred.; A task was canceled."**

{
		"@type": "ceasn:Competency",
	"^ceasn:skillEmbodied": {
		"^ceterms:targetNode": {
		 		"^ceterms:teaches": {
					"^ceterms:targetLearningOpportunity": {
						"^ceterms:requires": {
							"ceterms:ctid": "ce-98d29a1e-58ea-49cd-9308-49a1863a9362"
						}
					}
				}
			}
		}
}

**This query is slower.**  It took 40,738 seconds.  Also, it brought back 58,526 results but according to the credential finder, it should upward of 74,000+ competencies.  See the home page of the Finder for counts https://credentialfinder.org/ 

{
	"@type": "ceasn:Competency"
}

**This one is still too slow at 7.176 seconds. It brings back 11, 243 results.**  
{
	"@type": "ceasn:Competency",
	"^ceterms:targetNode": {
		"^ceterms:teaches": "search:anyValue"
	}
}

**This one is reasonable at 2.72 seconds. It brings back 188 results.**

{
	"@type": "ceasn:Competency",
	"^ceterms:targetNode": {
		"^ceterms:teaches": {
			"^ceterms:targetLearningOpportunity": {
				"^ceterms:requires": {
					"ceterms:ctid": "ce-98d29a1e-58ea-49cd-9308-49a1863a9362"
				}
			}
		}
	}
}

**Comment by jeannekitchens** [comment]
@excelsior @edgarf @science what has been deployed to improve queries?  Some of the queries are faster.  The query below is still very slow.  

{
"@type": "ceasn:Competency",
"^ceasn:skillEmbodied": {
"^ceterms:targetNode": {
"^ceterms:teaches": {
"^ceterms:targetLearningOpportunity": {
"^ceterms:requires": {
"ceterms:ctid": "ce-98d29a1e-58ea-49cd-9308-49a1863a9362"
}
}
}
}
}
}

**Comment by excelsior** [comment]
@jeannekitchens I finally optimized this one. Am proceeding with optimizing description set generation the similar way.

**Comment by jeannekitchens** [comment]
@excelsior @siuc-nate the above queries are all bringing back results in under 2 seconds.  Thank you @excelsior !

**Comment by siuc-nate** [comment]
This query (from the original post) now works:
```
{
	"ceterms:instructionalProgramType": "search:anyValue",
	"ceterms:ownedBy": "search:anyValue",
	"ceterms:offeredBy": "search:anyValue"
}
```

However, this query from [this post](https://github.com/CredentialEngine/CredentialRegistry/issues/670#issuecomment-1896225368) still times out:
```
{
	"@type": "ceasn:Competency",
	"^ceterms:targetNode":	{
		"^ceterms:targetCompetency": {
			"^ceterms:requires": "search:anyValue"
		}
	}
}
```

**Comment by excelsior** [comment]
@siuc-nate The last timing-out one has been optimized, too.

**Comment by siuc-nate** [comment]
That one is working now too. Thanks.
